name: "JustLeave.work"

on: [push , pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Update Composer
      run: composer update --ignore-platform-reqs -vvv
    - name: Install Dependencies
      run: composer install  -q --no-ansi --ignore-platform-reqs --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate Application Key
      run: php artisan key:generate
    - name: Run PHPUnit
      run: php artisan test tests/Feature

